### ISSUE TITLE
Update to 1.2.0 failed

### ISSUE THREAD

**Issue by fly74** [cmuche/octoprint-timelapseplus#59]
Hi Devs,

the update to 1.2.0 failed because of pillow, what can I do?

Log:
```
2023-05-12 19:29:42,480 ! During handling of the above exception, another exception occurred:
2023-05-12 19:29:42,481 ! 
2023-05-12 19:29:42,481 ! Traceback (most recent call last):
2023-05-12 19:29:42,481 ! File "<string>", line 2, in <module>
2023-05-12 19:29:42,481 ! File "<pip-setuptools-caller>", line 34, in <module>
2023-05-12 19:29:42,481 ! File "/tmp/pip-install-y6n37m0t/pillow_a049a5758b1948dfaed76d1de5c9ef9d/setup.py", line 903, in <module>
2023-05-12 19:29:42,481 ! raise RequiredDependencyException(msg)
2023-05-12 19:29:42,481 ! __main__.RequiredDependencyException:
2023-05-12 19:29:42,481 ! 
2023-05-12 19:29:42,481 ! The headers or library files could not be found for zlib,
2023-05-12 19:29:42,482 ! a required dependency when compiling Pillow from source.
2023-05-12 19:29:42,482 ! 
2023-05-12 19:29:42,482 ! Please see the install instructions at:
2023-05-12 19:29:42,482 ! https://pillow.readthedocs.io/en/latest/installation.html
2023-05-12 19:29:42,482 ! 
2023-05-12 19:29:42,482 ! 
2023-05-12 19:29:42,482 ! [end of output]
2023-05-12 19:29:42,482 ! 
2023-05-12 19:29:42,482 ! note: This error originates from a subprocess, and is likely not a problem with pip.
2023-05-12 19:29:42,482 ! error: legacy-install-failure
2023-05-12 19:29:42,483 ! 
2023-05-12 19:29:42,483 ! × Encountered error while trying to install package.
2023-05-12 19:29:42,483 ! ╰─> pillow
2023-05-12 19:29:42,483 ! 
2023-05-12 19:29:42,483 ! note: This is an issue with the package mentioned above, not pip.
2023-05-12 19:29:42,483 ! hint: See above for output from the failure.
2023-05-12 19:29:42,484 > Running setup.py install for pillow: finished with status 'error'
2023-05-12 19:29:42,485 > Rolling back uninstall of Pillow
```

**Comment by cmuche** [comment]
Hi @fly74 
Thanks for your input. Didn't encounter the problem at all. 
Seems to be a problem when installing Pillow. Please consider the suggested help page as it couldn't find zlib: https://pillow.readthedocs.io/en/latest/installation.html

Did you try uninstalling and installing again? Do you maybe have other plugins enabled which conflict with Pillow?

**Comment by fly74** [comment]
I tried it, but the same result. Version 1.19.9 works perfect.

**Comment by cmuche** [comment]
Which version of 1.19.9 do you mean? There is no Timelapse+ version like this...

**Comment by fly74** [comment]
Sorry wrong Plugin. This is the working version:

![Screenshot 2023-05-14 192034](https://github.com/cmuche/octoprint-timelapseplus/assets/38754941/11a86d9b-51a3-4821-a1fe-e0da8e9f9494)

**Comment by cmuche** [comment]
Hm, 1.1.0 to 1.2.0 didn't change anything on the Pillow dependency. But I saw it references a quite old version.

Maybe you could try to install it manually with this URL? This has an updated dependency.
https://github.com/cmuche/octoprint-timelapseplus/archive/refs/heads/v1.2.1.zip

Uninstalling/Installing didn't work and installing zlib via the command didn't work as well?

**Comment by fly74** [comment]
Hey Chris this works:

```
Successfully built TimelapsePlus
Installing collected packages: pillow, deepdiff, TimelapsePlus
Attempting uninstall: pillow
Found existing installation: Pillow 9.4.0
Uninstalling Pillow-9.4.0:
Successfully uninstalled Pillow-9.4.0
Successfully installed TimelapsePlus-1.2.0 deepdiff-6.3.0 pillow-9.5.0
Fertig!
```

**Comment by fly74** [comment]
> Okay - I'll include this fix in the next patch. Thanks for your input!

No problem. I see it's out 1.2.1 thumbs up!
